### PR TITLE
progressbar/iocopy: initial implementations

### PR DESCRIPTION
**Pull request by cgonyeo**
This commit adds the progressbar and iocopy files. progressbar exposes
an API for multiline progress bars, which is much simpler than the
current ioprogress API. Ideally the current API can be phased out in
favor of this one in the future.

iocopy provides a utility for performing parallel io.Copy calls, and
using the code in progressbar to draw progress bars about the transfers.

### CODE REVIEW

**Comment by cgonyeo** [comment]
Necessary for https://github.com/appc/docker2aci/issues/146.

**Comment by cgonyeo** [comment]
Oh, and it looks like this:

```
derek@proton ~/go/src/github.com/appc/docker2aci> ./bin/docker2aci docker://timhaak/plex
Downloading sha256:b34897ca2c0 [==============               ] 25.6 MB / 50.9 MB
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:3c40ae3d67f [=============================]     760 B / 760 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:92d77218248 [=============================]     219 B / 219 B
Downloading sha256:a2c847abd95 [=============================]     682 B / 682 B
Downloading sha256:243ba937422 [==                           ]  12.3 MB / 155 MB
Downloading sha256:9af0e2954b9 [=============================] 1.69 KB / 1.69 KB
Downloading sha256:dec30a75df3 [=============================] 1.73 KB / 1.73 KB
```

**Comment by jonboulle** [comment]
a thought, at this point should we just have a new project and abandon this one? If it's an entirely new API and doesn't touch any existing code..

**Comment by jonboulle** [comment]
Could you add some example code/output of how to use this?

**Comment by jzelinskie** [comment]
> a thought, at this point should we just have a new project and abandon this one? If it's an entirely new API and doesn't touch any existing code..

Why not consolidate on [cheggaaa/pb](https://github.com/cheggaaa/pb)? It seems to handle everything and handles some ugly crossplatform corner cases (I've personally already [fixed one](https://github.com/cheggaaa/pb/pull/55)).

**Comment by cgonyeo** [comment]
Without looking at the project too closely, I'd prefer to stick with this implementation if no one feels too strongly about it. Their multiline progress bars are described as "experimental and unstable", and I've already finished the docker2aci work to make it use this.

**Comment by cgonyeo** [comment]
> should we just have a new project and abandon this one?

I think I'd prefer to only have one codebase in CoreOS for drawing progress bars, and I'd be fine with doing the work to make everything use this new API once I hammer on it a little more (I've got a followup PR or two to make).

**Comment by jonboulle** [comment]
Just seems a bit silly for this still to be a "fork" of mitchellh/ioprogress when it's entirely new code

**Comment by jonboulle** [comment]
per OOB, let's put this in coreos/pkg

**Pull request closed without merging**
